### ISSUE TITLE
Στοιχεία επικοινωνίας Lila Villas

### ISSUE THREAD

**Issue by dimitrisdervas** [dimitrisdervas/lilavillas#1]
Θα ήθελα ότι υπάρχει από επικοινωνία:
- τηλέφωνο:
- οδό - περιοχή:
- κινητό( αν υπάρχει):
- facebook:
- twitter:
- instagram:
- gps coordinates - google map συντεταγμένες:

**Comment by rovithakis** [comment]
αναμονή

**Comment by rovithakis** [comment]
τηλ κινητό        +30 6976683314
 οδό - περιοχή:Palea Ethniki Odos Kissamou Chanion 32, Stalos, 73100, Greece
gps coordinates - google map συντεταγμένες: δεν ξέρω να τις βρω δες αν θες εδώ:
http://www.booking.com/hotel/gr/lila-villas.en-gb.html?label=gen173nr-17CAsoXEILbGlsYS12aWxsYXNIM2IFbm9yZWZoXIgBAZgBCLgBBMgBBNgBAegBAfgBCw;sid=69dd533967c84b9e728d593d2bd020b8;dcid=4;sb_price_type=total;type=total&;lang=en-gb#map_opened-show_id1535455

social media δεν έχουμε προς το παρών

**Comment by dimitrisdervas** [comment]
ok - Τα πέρασα

Τσέκαρέ τα
http://dimitrisdervas.github.io/lilavillas/pages/contact.html
http://dimitrisdervas.github.io/lilavillas/pages/reservation.html

**Comment by rovithakis** [comment]
ok
