### ISSUE TITLE
Facilities

### ISSUE THREAD

**Issue by rovithakis** [dimitrisdervas/lilavillas#10]
Νομίζω πως πρέπει ή να βγάλουμε τις περιγραφές από Lila paradise και Lila2 ή να βάλουμε περιγραφή και στο beach bungalow 
"Your romantic getaway by the sea.
1 bedroom, sleeps 2-3 persons."
Μάλλον το δεύτερο

**Comment by dimitrisdervas** [comment]
Την έβαλα
