### ISSUE TITLE
Πρόταση για τιτλους Villas

### ISSUE THREAD

**Issue by dimitrisdervas** [dimitrisdervas/lilavillas#13]
Δε ξερω πως σας ακούγεται - επιδή δε μου άρεσε το Lila2

**Villa Lila**
**Villa Paradise**
**Beach Bungalow**

**Comment by rovithakis** [comment]
Είναι αίτημα του ιδιοκτήτη να μην αλλάξουν τα όνοματα

**Comment by dimitrisdervas** [comment]
ok
