### ISSUE TITLE
Πρόταση - ερωτήση / Μου φάινεται δύσκολο όταν βλέπω τις φωτο μιας βιλας να δω της άλλης

### ISSUE THREAD

**Issue by dimitrisdervas** [dimitrisdervas/lilavillas#14]
Πρέπει να κάνω να ανοιξω το μενου να φορτωσω την άλλη σελίδα και να πατήσω στο λινκ gallery

Έχω μια ιδέα θα δοκιμάσω να σας τη δείξω

**Comment by rovithakis** [comment]
Δεν ενθουσιάζομαι... Κάνεις το ίδιο με το accommodation και στo galleries - μου φαίνεται επανάληψη για την αριστερή στήλη... Αλλά αν κάποιος θέλει να μπει σε συγκεκριμένο σπίτι, τότε μπαίνει από το accommodation και βλέπει το gallery.
Εναλλακτικά θα μπορούσε να μείνει εκεί το galleries και να δείχνει όλες τις φωτογραφίες χωρίς διαχωρισμό... Ασε που αμα τις διαχωρίζεις φαίνονται λίγες...
